---
- name: Deploy High Availability Application and Monitoring Cluster Stack
  hosts: aws_targets
  become: true
  gather_facts: true

  tasks:
    - name: Install Docker engine and Python dependencies
      dnf:
        name:
          - docker
          - python3-docker
        state: latest

    - name: Start Docker system engine
      service:
        name: docker
        state: started
        enabled: true

    - name: Launch live production Nginx application container
      docker_container:
        name: my_web_container
        image: nginxdemos/hello
        state: started
        restart_policy: always
        published_ports:
          - "80:80"

    - name: Force delete any stale Grafana containers and local storage data
      docker_container:
        name: metrics_grafana
        state: absent

    - name: Launch fresh Grafana Visual Dashboard analytics matrix container
      docker_container:
        name: metrics_grafana
        image: grafana/grafana-oss:latest
        state: started
        restart_policy: always
        published_ports:
          - "3000:3000"
        env:
          GF_SECURITY_ADMIN_USER: "admin"
          GF_SECURITY_ADMIN_PASSWORD: "AdminPassword123"
