---
- name: Transform EC2 into a Docker Host and Deploy App
  hosts: aws_targets
  become: true
  gather_facts: true

  tasks:
    - name: Install Docker dependencies and core package
      dnf:
        name: docker
        state: latest

    - name: Ensure Docker service is started and enabled on boot
      service:
        name: docker
        state: started
        enabled: true

    - name: Install python3-pip to manage Docker SDK
      dnf:
        name: python3-pip
        state: present

    - name: Install Ansible Docker library via pip
      pip:
        name: docker
        extra_args: --break-system-packages

    - name: Pull and launch a containerized sample web application
      docker_container:
        name: my_web_container
        image: nginxdemos/hello
        state: started
        restart_policy: always
        published_ports:
          - "80:80"
